### ISSUE TITLE
[FEAT] CarPlay UI

### ISSUE THREAD

**Issue by deslog** [deslog/MC2-Team1-DMGJ#4]
# Discription
CarPlay 화면 내부의 이미지와 '기록하기'버튼 UI 구현

# Todo

- [ ] Carplay entitlement 설정
- [ ] Carplay 내부 map or image 생성
- [ ] Carplay 네비게이션 바 버튼 생성

# ETC 
- entitlement가 maps 인지 content인지 판단 후 사용해야할 필요가 있음.
- 네비게이션 바 버튼 두개 넣을지, 한개 넣을지 확인 필요
